# Generated by Django 5.2 on 2025-05-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_timerecord_hours_worked'),
    ]

    operations = [
        migrations.AddField(
            model_name='timerecord',
            name='biweekly_total_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='timerecord',
            name='rate_per_hour',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
