# Generated by Django 5.2 on 2025-05-07 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_timerecord_biweekly_total_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timerecord',
            name='total_paused_time',
            field=models.FloatField(default=0),
        ),
    ]
