# Generated by Django 5.2 on 2025-05-08 13:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_timerecord_total_paused_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='PauseReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('pause_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pauses', to='employee.timerecord')),
            ],
        ),
    ]
