# Generated by Django 5.2 on 2025-05-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_pauserecord_delete_pausereason'),
    ]

    operations = [
        migrations.AddField(
            model_name='pauserecord',
            name='resume_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
