# Generated by Django 5.2 on 2025-05-08 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_pauserecord_resume_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pauserecord',
            name='time_record',
        ),
    ]
