# Generated by Django 5.2 on 2025-05-10 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_remove_pauserecord_time_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='pauserecord',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
