# Generated by Django 5.2 on 2025-05-10 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_pauserecord_duration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timerecord',
            name='biweekly_total_hours',
        ),
        migrations.RemoveField(
            model_name='timerecord',
            name='rate_per_hour',
        ),
        migrations.CreateModel(
            name='UserWorkProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_per_hour', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('biweekly_total_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='work_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
