# Generated by Django 5.2 on 2025-05-11 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_timerecord_is_paused'),
    ]

    operations = [
        migrations.AddField(
            model_name='timerecord',
            name='check_in_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
