# Generated by Django 5.2 on 2025-10-08 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_timerecord_check_in_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timerecord',
            name='is_paused',
        ),
        migrations.RemoveField(
            model_name='timerecord',
            name='total_paused_time',
        ),
        migrations.DeleteModel(
            name='PauseRecord',
        ),
    ]
