# Generated by Django 5.2 on 2025-12-03 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('superuser', 'Super User'), ('caregiver', 'Caregiver'), ('coordinator', 'Care Coordinator'), ('manager', 'Manager')], default='caregiver', max_length=20),
        ),
    ]
