# Generated by Django 5.2 on 2025-12-02 01:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='hours_to_pay',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99.999)]),
        ),
    ]
