# Generated by Django 5.2 on 2025-10-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evv', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitlog',
            old_name='end_lat',
            new_name='check_in_lat',
        ),
        migrations.RenameField(
            model_name='visitlog',
            old_name='end_lng',
            new_name='check_in_lng',
        ),
        migrations.RenameField(
            model_name='visitlog',
            old_name='start_lat',
            new_name='check_out_lat',
        ),
        migrations.RenameField(
            model_name='visitlog',
            old_name='start_lng',
            new_name='check_out_lng',
        ),
        migrations.RenameField(
            model_name='visitlog',
            old_name='notes',
            new_name='visit_notes',
        ),
        migrations.RemoveField(
            model_name='visitlog',
            name='check_in',
        ),
        migrations.RemoveField(
            model_name='visitlog',
            name='check_out',
        ),
        migrations.RemoveField(
            model_name='visitlog',
            name='service',
        ),
        migrations.RemoveField(
            model_name='visitlog',
            name='verified',
        ),
        migrations.AddField(
            model_name='visitlog',
            name='check_in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitlog',
            name='check_out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitlog',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='visit_logs', to='evv.service'),
        ),
        migrations.AddField(
            model_name='visitlog',
            name='status',
            field=models.CharField(choices=[('checked_in', 'Checked In'), ('completed', 'Completed')], default='checked_in', max_length=20),
        ),
    ]
