# Generated by Django 5.2 on 2025-12-02 01:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evv', '0002_alter_visit_hours_to_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='hours_to_bill',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='visit',
            name='hours_to_pay',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
