# Generated by Django 5.2 on 2025-10-08 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evv', '0002_rename_end_lat_visitlog_check_in_lat_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ('last_name', 'first_name')},
        ),
        migrations.AlterModelOptions(
            name='visitlog',
            options={'ordering': ('-created_at',)},
        ),
    ]
