# Generated by Django 5.2 on 2025-12-02 14:34

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evv', '0003_alter_visit_hours_to_bill_alter_visit_hours_to_pay'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientemployeexref',
            options={'verbose_name': 'Client-Employee Relationship', 'verbose_name_plural': 'Client-Employee Relationships'},
        ),
        migrations.AddField(
            model_name='clientemployeexref',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientemployeexref',
            name='end_date',
            field=models.DateField(blank=True, help_text='Date when relationship ended (NULL for ongoing)', null=True),
        ),
        migrations.AddField(
            model_name='clientemployeexref',
            name='evv_submission_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientemployeexref',
            name='evv_submission_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientemployeexref',
            name='live_in',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=5),
        ),
        migrations.AddField(
            model_name='clientemployeexref',
            name='modifier1',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='clientemployeexref',
            name='modifier2',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='clientemployeexref',
            name='modifier3',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='clientemployeexref',
            name='modifier4',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='clientemployeexref',
            name='payer_id',
            field=models.CharField(choices=[('AZACH', 'AZACH'), ('AZBUFC', 'AZBUFC'), ('AZCCCS', 'AZCCCS'), ('AZCDMP', 'AZCDMP'), ('AZDDD', 'AZDDD'), ('AZMCC', 'AZMCC'), ('AZMYC', 'AZMYC'), ('AZSHC', 'AZSHC'), ('AZUCP', 'AZUCP')], default='AZDDD', max_length=10),
        ),
        migrations.AddField(
            model_name='clientemployeexref',
            name='payer_program',
            field=models.CharField(default='AHCCCS', help_text="Must be 'AHCCCS' per spec", max_length=20),
        ),
        migrations.AddField(
            model_name='clientemployeexref',
            name='procedure_code',
            field=models.CharField(default=django.utils.timezone.now, help_text='HCPCS code (see Section 10.10 of spec)', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientemployeexref',
            name='relationship',
            field=models.CharField(choices=[('Spouse', 'Spouse'), ('Adult children/Stepchildren', 'Adult children/Stepchildren'), ('Son-in-law/Daughter-in-law', 'Son-in-law/Daughter-in-law'), ('Grandchildren', 'Grandchildren'), ('Siblings/Step siblings', 'Siblings/Step siblings'), ('Parents/Adoptive Parents/Legal Guardians', 'Parents/Adoptive Parents/Legal Guardians'), ('Stepparents', 'Stepparents'), ('Grandparents', 'Grandparents'), ('Mother-in-law/Father-in-law', 'Mother-in-law/Father-in-law'), ('Brother-in-law/Sister-in-law', 'Brother-in-law/Sister-in-law'), ('Other', 'Other')], default='Other', max_length=64),
        ),
        migrations.AddField(
            model_name='clientemployeexref',
            name='sequence_id',
            field=models.IntegerField(default=1, help_text='Incremented for each update'),
        ),
        migrations.AddField(
            model_name='clientemployeexref',
            name='start_date',
            field=models.DateField(default=datetime.date.today, help_text='Date when relationship began'),
        ),
        migrations.AddField(
            model_name='clientemployeexref',
            name='submitted_to_evv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientemployeexref',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='clientemployeexref',
            name='xref_other_id',
            field=models.CharField(default='XREF0001', help_text='Unique identifier in external system', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
