# Generated by Django 5.2 on 2025-12-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evv', '0004_alter_clientemployeexref_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientemployeexref',
            name='live_in',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10),
        ),
        migrations.AlterField(
            model_name='clientemployeexref',
            name='procedure_code',
            field=models.CharField(help_text='HCPCS code (see Section 10.10 of spec)', max_length=10),
        ),
    ]
